/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduler;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JFrame;

/**
 *
 * @author Hangry
 */
public class NetbeansGUI extends JFrame {

	private final JPanel[] sidePanels;
    private final JPanel[] changingPanels;

    /**
     * Creates new form CalProJFrame
     */
    public NetbeansGUI() {
        initComponents();
        changingPanels = new JPanel[]{this.changingViewPanel, this.changingComparePanel, this.changingInfoPanel, this.changingHelpPanel};
        sidePanels = new JPanel[]{this.viewPanel, this.comparePanel, this.classInfoPanel, this.helpPanel};

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        viewPanel = new javax.swing.JPanel();
        viewLabel = new javax.swing.JLabel();
        viewIcon = new javax.swing.JLabel();
        comparePanel = new javax.swing.JPanel();
        compareLabel = new javax.swing.JLabel();
        compareIcon = new javax.swing.JLabel();
        classInfoPanel = new javax.swing.JPanel();
        classInfoLabel = new javax.swing.JLabel();
        classInfoIcon = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        helpLabel = new javax.swing.JLabel();
        helpIcon = new javax.swing.JLabel();
        exitLable = new javax.swing.JLabel();
        changingViewPanel = new javax.swing.JPanel();
        scheduleNameLabel = new javax.swing.JLabel();
        viewImportIcon = new javax.swing.JLabel();
        viewExportIcon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewScheduleTable = new javax.swing.JTable();
        changingComparePanel = new javax.swing.JPanel();
        scheduleNameLabel2 = new javax.swing.JLabel();
        compareImportIcon = new javax.swing.JLabel();
        changingInfoPanel = new javax.swing.JPanel();
        scheduleNameLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoHTMLView = new javax.swing.JEditorPane();
        changingHelpPanel = new javax.swing.JPanel();
        scheduleNameLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 0, 153));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        viewLabel.setForeground(new java.awt.Color(0, 0, 153));
        viewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewLabel.setText("View");
        viewLabel.setIconTextGap(0);
        viewLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewLabelMouseClicked(evt);
            }
        });

        viewIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/assests/Blue_Menu_icon.png"))); // NOI18N
        viewIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addComponent(viewIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(viewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 330, 50));

        comparePanel.setBackground(new java.awt.Color(255, 255, 255));

        compareLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        compareLabel.setForeground(new java.awt.Color(0, 0, 153));
        compareLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compareLabel.setText("Compare");
        compareLabel.setIconTextGap(0);
        compareLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compareIconMouseClicked(evt);
            }
        });

        compareIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compareIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/assests/Blues_scales_icon.png"))); // NOI18N
        compareIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compareIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout comparePanelLayout = new javax.swing.GroupLayout(comparePanel);
        comparePanel.setLayout(comparePanelLayout);
        comparePanelLayout.setHorizontalGroup(
            comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparePanelLayout.createSequentialGroup()
                .addComponent(compareIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compareLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );
        comparePanelLayout.setVerticalGroup(
            comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(compareLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(compareIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(comparePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 50));

        classInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        classInfoLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        classInfoLabel.setForeground(new java.awt.Color(0, 0, 153));
        classInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classInfoLabel.setText("Class Info");
        classInfoLabel.setIconTextGap(0);
        classInfoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classInfoIconMouseClicked(evt);
            }
        });

        classInfoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classInfoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/assests/Blue_info_icon.png"))); // NOI18N
        classInfoIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classInfoIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout classInfoPanelLayout = new javax.swing.GroupLayout(classInfoPanel);
        classInfoPanel.setLayout(classInfoPanelLayout);
        classInfoPanelLayout.setHorizontalGroup(
            classInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classInfoPanelLayout.createSequentialGroup()
                .addComponent(classInfoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );
        classInfoPanelLayout.setVerticalGroup(
            classInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(classInfoIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(classInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 330, 50));

        helpPanel.setBackground(new java.awt.Color(255, 255, 255));

        helpLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(0, 0, 153));
        helpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel.setText("Help");
        helpLabel.setIconTextGap(0);
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });

        helpIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/assests/Blue_Help_Icon.png"))); // NOI18N
        helpIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addComponent(helpIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(helpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helpIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(helpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 330, 50));

        mainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 780));

        exitLable.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        exitLable.setForeground(new java.awt.Color(0, 0, 153));
        exitLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLable.setText("X");
        exitLable.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        exitLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLableMouseClicked(evt);
            }
        });
        mainPanel.add(exitLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 30, -1));

        changingViewPanel.setBackground(new java.awt.Color(255, 255, 0));
        


        scheduleNameLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        scheduleNameLabel.setForeground(new java.awt.Color(0, 0, 153));
        scheduleNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scheduleNameLabel.setText("No Schedule");

        viewImportIcon.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        viewImportIcon.setForeground(new java.awt.Color(0, 0, 153));
        viewImportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/assests/Blue_Add_Schedule_Icon.png"))); // NOI18N
        viewImportIcon.setText("Import Schedule");

        viewExportIcon.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        viewExportIcon.setForeground(new java.awt.Color(0, 0, 153));
        viewExportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/assests/Blue_Export_Icon.png"))); // NOI18N
        viewExportIcon.setText("Export to .ics");

        viewScheduleTable.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        viewScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ));
        viewScheduleTable.setAutoscrolls(false);
        viewScheduleTable.setEnabled(false);
        viewScheduleTable.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(viewScheduleTable);

        javax.swing.GroupLayout changingViewPanelLayout = new javax.swing.GroupLayout(changingViewPanel);
        changingViewPanel.setLayout(changingViewPanelLayout);
        changingViewPanelLayout.setHorizontalGroup(
            changingViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingViewPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(changingViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changingViewPanelLayout.createSequentialGroup()
                        .addComponent(scheduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)
                        .addGroup(changingViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewImportIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewExportIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(changingViewPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(changingViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane1))))
                .addGap(60, 60, 60))
        );
        changingViewPanelLayout.setVerticalGroup(
            changingViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingViewPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(changingViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewImportIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewExportIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        mainPanel.add(changingViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1030, 780));

        changingComparePanel.setBackground(new java.awt.Color(102, 102, 255));

        scheduleNameLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        scheduleNameLabel2.setForeground(new java.awt.Color(0, 0, 153));
        scheduleNameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scheduleNameLabel2.setText("No Schedule");

        compareImportIcon.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        compareImportIcon.setForeground(new java.awt.Color(0, 0, 153));
        compareImportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scheduler/assests/Blue_Add_Schedule_Icon.png"))); // NOI18N
        compareImportIcon.setText("Import Schedule");

        javax.swing.GroupLayout changingComparePanelLayout = new javax.swing.GroupLayout(changingComparePanel);
        changingComparePanel.setLayout(changingComparePanelLayout);
        changingComparePanelLayout.setHorizontalGroup(
            changingComparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changingComparePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(scheduleNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                .addComponent(compareImportIcon)
                .addGap(47, 47, 47))
        );
        changingComparePanelLayout.setVerticalGroup(
            changingComparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingComparePanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(changingComparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compareImportIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(676, Short.MAX_VALUE))
        );

        mainPanel.add(changingComparePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1030, 780));

        changingInfoPanel.setBackground(new java.awt.Color(0, 204, 51));

        scheduleNameLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        scheduleNameLabel3.setForeground(new java.awt.Color(0, 0, 153));
        scheduleNameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scheduleNameLabel3.setText("Class Information");

        infoHTMLView.setEditable(false);
        jScrollPane3.setViewportView(infoHTMLView);

        javax.swing.GroupLayout changingInfoPanelLayout = new javax.swing.GroupLayout(changingInfoPanel);
        changingInfoPanel.setLayout(changingInfoPanelLayout);
        changingInfoPanelLayout.setHorizontalGroup(
            changingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingInfoPanelLayout.createSequentialGroup()
                .addGroup(changingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changingInfoPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(scheduleNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changingInfoPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        changingInfoPanelLayout.setVerticalGroup(
            changingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingInfoPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(scheduleNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        mainPanel.add(changingInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1030, 780));

        
        changingHelpPanel.setBackground(new java.awt.Color(255, 51, 153));

        scheduleNameLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        scheduleNameLabel4.setForeground(new java.awt.Color(0, 0, 153));
        scheduleNameLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scheduleNameLabel4.setText("Help");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Testing out the text area");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout changingHelpPanelLayout = new javax.swing.GroupLayout(changingHelpPanel);
        changingHelpPanel.setLayout(changingHelpPanelLayout);
        changingHelpPanelLayout.setHorizontalGroup(
            changingHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingHelpPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(changingHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scheduleNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(changingHelpPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(changingHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        changingHelpPanelLayout.setVerticalGroup(
            changingHelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changingHelpPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(scheduleNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        mainPanel.add(changingHelpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1030, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );


        this.pack();
        

    }// </editor-fold>//GEN-END:initComponents

    private void exitLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLableMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLableMouseClicked

    private void viewLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLabelMouseClicked
        setColor(this.sidePanels, this.viewPanel);
        handleVisibility(this.changingPanels, this.changingViewPanel);
    }//GEN-LAST:event_viewLabelMouseClicked

    private void compareIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compareIconMouseClicked
        setColor(this.sidePanels, this.comparePanel);
        handleVisibility(this.changingPanels, this.changingComparePanel);
    }//GEN-LAST:event_compareIconMouseClicked

    private void classInfoIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classInfoIconMouseClicked
        setColor(this.sidePanels, this.classInfoPanel);
        handleVisibility(this.changingPanels, this.changingInfoPanel);
    }//GEN-LAST:event_classInfoIconMouseClicked

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        setColor(this.sidePanels, this.helpPanel);
        handleVisibility(this.changingPanels, this.changingHelpPanel);
    }//GEN-LAST:event_helpLabelMouseClicked

    
    void setColor(JPanel[] panels, JPanel panel) {
        for (JPanel panel1 : panels) {
            panel1.setBackground(new Color(255,255,255));
        }
        panel.setBackground(new Color(204,204,204));
    }
    
        private void handleVisibility(JPanel[] panels, JPanel vis) {
        for (JPanel panel : panels) {
            panel.setVisible(false);
        }
        vis.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetbeansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetbeansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetbeansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetbeansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NetbeansGUI mainFrame = new NetbeansGUI();
                mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel changingComparePanel;
    private javax.swing.JPanel changingHelpPanel;
    private javax.swing.JPanel changingInfoPanel;
    private javax.swing.JPanel changingViewPanel;
    private javax.swing.JLabel classInfoIcon;
    private javax.swing.JLabel classInfoLabel;
    private javax.swing.JPanel classInfoPanel;
    private javax.swing.JLabel compareIcon;
    private javax.swing.JLabel compareImportIcon;
    private javax.swing.JLabel compareLabel;
    private javax.swing.JPanel comparePanel;
    private javax.swing.JLabel exitLable;
    private javax.swing.JLabel helpIcon;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JEditorPane infoHTMLView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel scheduleNameLabel;
    private javax.swing.JLabel scheduleNameLabel2;
    private javax.swing.JLabel scheduleNameLabel3;
    private javax.swing.JLabel scheduleNameLabel4;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel viewExportIcon;
    private javax.swing.JLabel viewIcon;
    private javax.swing.JLabel viewImportIcon;
    private javax.swing.JLabel viewLabel;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JTable viewScheduleTable;
    // End of variables declaration//GEN-END:variables
}
